config/routes.rb
Rails.application.routes.draw do
  root "players#index"
  get "game(/:id)" => "game#index", as: :game_frame
  resources :players, :boosts, :buildings, :tickers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boost.rb
class Boost < ApplicationRecord
    has_many :boost_players
    has_many :players, through: :boost_players
end

app/models/boost_player.rb
class BoostPlayer < ApplicationRecord
    belongs_to :player
    belongs_to :boost
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :building_players
    has_many :players, through: :building_players
end

app/models/building_player.rb
class BuildingPlayer < ApplicationRecord
    belongs_to :player
    belongs_to :building
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :building_players
    has_many :buildings, through: :building_players
    has_many :boost_players
    has_many :boosts, through: :boost_players

    accepts_nested_attributes_for :buildings, :boosts
end

app/models/ticker.rb
class Ticker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Response
  include ExceptionHandler
end

app/controllers/bonus_controller.rb
class BonusController < ApplicationController
    before_action :set_bonus, only: [:show, :update, :destroy]
    skip_before_action :verify_authenticity_token

    def index
        @bonus = Bonus.all
        json_response(@bonus)
    end

    def create
        @bonus = Bonus.create!(bonus_params)
        json_response(@bonus, :created)
    end

    def show
        json_response(@bonus)
    end

    def update
        @bonus.update(bonus_params)
        head :no_content
    end

    def destroy
        @bonus.destroy
        head :no_content
    end

    private

    def bonus_params
        params.permit(:trigger, :text)
    end

    def set_bonus
        @bonus = Bonus.find(params[:id])
    end
end

app/controllers/boosts_controller.rb
class BoostsController < ApplicationController
    before_action :set_bonus, only: [:show, :update, :destroy]
    skip_before_action :verify_authenticity_token

    def index
        @boosts = Boost.all
        json_response(@boosts)
    end

    def create
        @boosts = Boost.create!(boosts_params)
        json_response(@boosts, :created)
    end

    def show
        json_response(@boosts)
    end

    def update
        # @boosts.update(boosts_params)
        # head :no_content

        @boost = Boost.find(params[:id])
        @boost.players << Player.find(params[:player_id])

        respond_to do |format|
            format.json { render :json => Player.find(params[:player_id]).to_json( :include => [:buildings, :boosts] ) }
        end
    end

    def destroy
        @boosts.destroy
        head :no_content
    end

    private

    def boosts_params
        params.permit(:trigger, :text)
    end

    def set_bonus
        @boosts = Boost.find(params[:id])
    end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
    before_action :set_building, only: [:show, :update, :destroy]
    skip_before_action :verify_authenticity_token

    def index
        @buildings = Building.all
        json_response(@buildings)
    end

    def create
        @building = Building.create!(building_params)
        json_response(@building, :created)
    end

    def show
        json_response(@building)
    end

    def update
        # @building.update(building_params)
        # head :no_content

        @building = Building.find(params[:id])
        @building.players << Player.find(params[:player_id])

        respond_to do |format|
            format.json { render :json => Player.find(params[:player_id]).to_json( :include => [:buildings, :boosts] ) }
        end
    end

    def destroy
        @building.destroy
        head :no_content
    end

    private

    def building_params
        params.permit(:icon, :name, :base_cost, :base_cookies_per_seconds)
    end

    def set_building
        @building = Building.find(params[:id])
    end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
    extend ActiveSupport::Concern
  
    included do
      rescue_from ActiveRecord::RecordNotFound do |e|
        json_response({ message: e.message }, :not_found)
      end
  
      rescue_from ActiveRecord::RecordInvalid do |e|
        json_response({ message: e.message }, :unprocessable_entity)
      end
    end
  end

app/controllers/concerns/response.rb
module Response
    def json_response(object, status = :ok)
        render json: object, status: status
    end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    @player = Player.find(params[:id])
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    before_action :set_player, only: [:show, :update, :destroy]
    skip_before_action :verify_authenticity_token

    def index
        @players = Player.all()
    end

    def details
        @player = Player.find(params[:id])
    end
    
    def new
    end

    def create
        @player = Player.new(player_params)
        @player.ruby_count = 0
        @player.clicks = 0
        @player.save

        @boost = Boost.where(base_cost:-1).first
        @boost.players << @player

        redirect_to players_path
    end

    def show
        respond_to do |format|
            format.html
            # format.json { json_response(@player) }
            format.json { render :json => @player.to_json( :include => [:buildings, :boosts] ) }
        end
        # json_response(@player)
    end

    def update
        @player.update(json_player_params)

        respond_to do |format|
            format.json { render :json => @player.to_json( :include => [:buildings, :boosts] ) }
        end
    end

    def destroy
        @player.destroy
        head :no_content
    end

private
    def set_player
        @player = Player.find(params[:id])
    end

    def json_player_params
        params.permit(:pseudo, :ruby_count, :clicks)
    end

    def player_params
        params.require(:player).permit(:pseudo)
    end
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
    before_action :set_ticker, only: [:show, :update, :destroy]
    skip_before_action :verify_authenticity_token

    def index
        @tickers = Ticker.all
        json_response(@tickers)
    end

    def create
        @ticker = Ticker.create!(ticker_params)
        json_response(@ticker, :created)
    end

    def show
        json_response(@ticker)
    end

    def update
        @ticker.update(ticker_params)
        head :no_content
    end

    def destroy
        @ticker.destroy
        head :no_content
    end

    private

    def ticker_params
        params.permit(:trigger, :text)
    end

    def set_ticker
        @ticker = ticker.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bonus_helper.rb
module BonusHelper
end

app/helpers/boosts_helper.rb
module BoostsHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/views/game/index.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    <title>Ruby Clicker</title>

    <%= stylesheet_link_tag "default.css" %>
    <%= stylesheet_link_tag "vuetify.min.css" %>
    <%= stylesheet_link_tag "core.css" %>

    <%= favicon_link_tag "/assets/ruby.png", rel: "icon", type: "image/png" %>

    <!-- <link rel="icon" type="image/png" href="/assets/ruby.png"> -->
    <link href="https://fonts.googleapis.com/css?family=Risque" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <div id="rubyclicker">
      <v-app>
        <v-content>
          <v-container class="bloc">
            <v-tabs light grow :scrollable="false">
              <v-tabs-bar class="rg-light-gray">
                <v-tabs-slider class="rg-blue"></v-tabs-slider>
                <v-tabs-item key="main" href="main">Game</v-tabs-item>
                <v-tabs-item key="statistic" href="statistic">Stats</v-tabs-item>
              </v-tabs-bar>
              <v-tabs-items>
                <v-tabs-content id="main">
                  <!-- ruby container -->
                  <v-container class="bloc">
                    <v-layout row elevation-2>
                      <v-flex>
                        <v-card flat tile>
                          <v-card-text id="rubyTitle" v-bind="ruby">{{ shortMoney(ruby) + " rub" + (ruby > 1 ? "ies" : "y") }} / <small>per second : {{ shortMoney(CpS) }}</small></v-card-text>
                          <v-card-text style="height: 400px;">
                            <div @click="createRuby()" id="target">
                              <div class="bg"></div>
                              <div class="overlay"></div>
                            </div>
                          </v-card-text>
                        </v-card>
                      </v-flex>
                    </v-layout>

                    <!-- reputation -->
                    <v-layout row elevation-2>
                      <v-flex>
                        <v-card flat tile dark>
                          <v-card-text>
                            <center>&#171; {{ (components.tickers.filter((ticker) => { return manufacturedRuby >= ticker.cost }).slice(-1).pop() || { description: "" }).description }} &#187;</center>
                          </v-card-text>
                        </v-card>
                      </v-flex>
                    </v-layout>
                  </v-container>

                  <v-container class="bloc">
                    <!-- bonus availables -->
                    <v-subheader>Shop</v-subheader>
                    <v-layout row wrap text-xs-center elevation-2 style="background: white;">
                      <v-flex xs3 v-for="(item, key, index) in components.bonus" v-if="showBonus(item), item.cost == -1 || (item.active && !item.buy)">
                        <v-card tile flat>
                          <v-list two-line class="pa-0">
                            <v-list-tile @click="selectedMode = key">
                              <v-list-tile-avatar>
                                <v-icon class="vj-fa material-icons icon" v-bind:class="{ 'error--text': key == selectedMode }">{{ "fa-" + item.icon }}</v-icon>
                              </v-list-tile-avatar>
                              <v-list-tile-content>
                                <v-list-tile-title v-bind:class="{ 'error--text': key == selectedMode }">{{ item.title }}</v-list-tile-title>
                                <v-list-tile-sub-title>{{ item.subtitle }}</v-list-tile-sub-title>
                              </v-list-tile-content>
                            </v-list-tile>
                          </v-list>
                        </v-card>
                      </v-flex>
                    </v-layout>

                    <v-layout row elevation-2>
                      <v-flex>
                        <v-card tile flat dark v-bind="selectedMode">
                          <v-card-text>
                            <h2>{{ selectedMode ? components.bonus[selectedMode].title : "" }}</h2>
                          </v-card-text>
                          <v-card-text>
                            <small>{{ selectedMode ? components.bonus[selectedMode].subtitle : "" }}</small><br>
                            <span v-html="selectedMode ? components.bonus[selectedMode].description : ''"></span>
                          </v-card-text>
                          <v-card-text>
                             <v-btn v-if="selectedMode && !components.bonus[selectedMode].buy" color="error" @click="addBonus(components.bonus[selectedMode])">Buy for {{ shortMoney(components.bonus[selectedMode].cost) }} <img class="mini-ruby" src="/assets/ruby.png"></v-btn>
                          </v-card-text>
                        </v-card>
                      </v-flex>
                    </v-layout>

                    <!-- buildings -->
                    <v-subheader>Buildings</v-subheader>
                    <v-layout row wrap text-xs-center elevation-2>
                      <v-flex xs3 v-for="(item, key, index) in components.buildings">
                        <v-card tile flat>
                          <v-list v-if="item.active" two-line class="pa-0">
                            <v-list-tile @click="addItem(item)" class="yellow lighten-4">
                              <v-list-tile-avatar>
                                <v-icon class="vj-fa material-icons icon">{{ "fa-" + item.icon }}</v-icon>
                              </v-list-tile-avatar>
                              <v-list-tile-content>
                                <v-list-tile-title>{{ item.title }} <small><strong>[{{ item.counter }}]</strong></small></v-list-tile-title>
                                <v-list-tile-sub-title v-bind="item.counter">{{ shortMoney(cumulativePrice(item.cost, item.counter)) + " rubies" }}</v-list-tile-sub-title>
                              </v-list-tile-content>
                            </v-list-tile>
                          </v-list>

                          <v-list v-else two-line class="pa-0" style="opacity: 0.3" v-bind="ruby">
                            <v-list-tile class="yellow lighten-4">
                              <v-list-tile-avatar>
                                <v-icon class="vj-fa material-icons icon">fa-question</v-icon>
                              </v-list-tile-avatar>
                              <v-list-tile-content>
                                <v-list-tile-title>{{ showItem(item) }} ???</v-list-tile-title>
                                <v-list-tile-sub-title>{{ shortMoney(item.cost) + " rubies" }}</v-list-tile-sub-title>
                              </v-list-tile-content>
                            </v-list-tile>
                          </v-list>
                        </v-card>
                      </v-flex>
                    </v-layout>
                  </v-container>
                </v-tabs-content>
                <v-tabs-content id="statistic">
                  <!-- general stats -->
                  <v-subheader>General</v-subheader>
                  <v-layout row elevation-2>
                    <v-flex>
                      <v-card tile flat dark>
                        <v-card-text>
                          <span v-bind="ruby">Rubies in bank : {{ shortMoney(ruby) }}</span><br>
                          <span v-bind="manufacturedRuby">Rubied baked : {{ shortMoney(manufacturedRuby) }}</span><br>
                          <span v-bind="buildingsOwned">{{ "Building" + (buildingsOwned > 1 ? "s" : "") + " owned : " + buildingsOwned }}</span><br>
                          <span v-bind="CpS">Rubies per second : {{ shortMoney(CpS) }}</span><br>
                          <span v-bind="click">Rubies per click : {{ click }}</span><br>
                          <span v-bind="rubyClick">Rubies clicks : {{ rubyClick }}</span>
                        </v-card-text>
                      </v-card>
                    </v-flex>
                  </v-layout>

                  <!-- Bonus unlocked -->
                  <v-subheader>Bonus unlocked</v-subheader>
                  <v-layout row wrap text-xs-center elevation-2 style="background: white;">
                    <v-list two-line>
                      <v-list-tile avatar v-for="item in components.bonus" v-if="item.buy">
                        <v-list-tile-avatar>
                          <v-icon class="vj-fa material-icons icon">{{ "fa-" + item.icon }}</v-icon>
                        </v-list-tile-avatar>
                        <v-list-tile-content>
                          <v-list-tile-title>{{ item.title }}</v-list-tile-title>
                          <v-list-tile-sub-title v-html="item.description"></v-list-tile-sub-title>
                        </v-list-tile-content>
                      </v-list-tile>
                    </v-list>
                  </v-layout>
                </v-tabs-content>
              </v-tabs-items>
            </v-tabs>
          </v-container>
        </v-content>
      </v-app>
    </div>

    <%= javascript_include_tag "vue.min" %>
    <%= javascript_include_tag "vuetify.min" %>
    <%= javascript_include_tag "fetch" %>
    <%= javascript_include_tag "core" %>

    </body>
</html>

app/views/players/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    <title>Ruby Clicker</title>

    <%= stylesheet_link_tag "default.css" %>
    <%= stylesheet_link_tag "vuetify.min.css" %>

    <%= favicon_link_tag "/assets/ruby.png", rel: "icon", type: "image/png" %>

    <!-- <link rel="icon" type="image/png" href="/assets/ruby.png"> -->
    <link href="https://fonts.googleapis.com/css?family=Risque" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <div id="homepage">
      <v-app>
        <v-content>
          <v-container class="bloc">
            <h1 class="mb-4">
              <center>Choose your player :</center>
            </h1>
         
            <!-- <table>
              <tr>
                <th>Pseudonyme</th>
                <th>Rubies in bank</th>
              </tr>
             
              <% @players.each do |player| %>
                <tr>
                  <td><%= player.pseudo %></td>
                  <td><%= player.ruby_count %></td>
                  <td><%= link_to 'Details', player_path(player) %></td>
                  <td><%= link_to 'Play !', game_frame_url(player) %></td>
                </tr>
              <% end %>
            </table>

            <%= link_to 'Hey I\'m new ! Create an account.'  , new_player_path %> -->

            <v-data-table
                v-bind:headers="headers"
                :items="items"
                class="elevation-1"
              >
              <template slot="headerCell" slot-scope="props">
                <v-tooltip bottom>
                  <span slot="activator">
                    {{ props.header.text }}
                  </span>
                  <span>
                    {{ props.header.text }}
                  </span>
                </v-tooltip>
              </template>
              <template slot="items" slot-scope="props">
                <td>{{ props.item.pseudo }}</td>
                <td class="text-xs-right">{{ props.item.ruby_count }}</td>
                <td class="text-xs-right">{{ props.item.clicks }}</td>
                <td class="text-xs-right" v-html="props.item.options"></td>
              </template>
            </v-data-table>

            <v-alert class="mt-4" color="warning" icon="priority_high" dismissible v-model="alert" value="true">
              Hey I'm new! <a href="<%= new_player_path %>">Create an account</a>.
            </v-alert>
          </v-container>
        </v-content>
      </v-app>
    </div>

    <%= javascript_include_tag "vue.min" %>
    <%= javascript_include_tag "vuetify.min" %>

    <script type="text/javascript">
      var homepage = new Vue({
        el: "#homepage",
        data: {
          alert: true,
          headers: [
            {
              text: "Pseudonyme",
              align: "left",
              value: "pseudo"
            },
            { text: "Rubies in bank", value: "ruby_count" },
            { text: "Total of clicks", value: "clicks" },
            { text: "Options", value: "options" }
          ],
          items: <%= raw @players.to_json %>.map(player => {
            player.options = 
              "<a href=\"<%= Rails.application.routes.url_helpers.players_path %>/" + player.id + "\">Details</a>\
              <br>\
              <a href=\"/game/" + player.id + "\">Play</a>";
            return player;
          })
        }
      });
    </script>
  </body>
</html>

app/views/players/new.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    <title>Ruby Clicker</title>

    <%= stylesheet_link_tag "default.css" %>
    <%= stylesheet_link_tag "vuetify.min.css" %>

    <%= favicon_link_tag "/assets/ruby.png", rel: "icon", type: "image/png" %>

    <!-- <link rel="icon" type="image/png" href="/assets/ruby.png"> -->
    <link href="https://fonts.googleapis.com/css?family=Risque" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	</head>
	<body>
		<div id="suscribe">
      <v-app>
        <v-content>
          <v-container class="bloc">
						<h1 class="mb-4">
              <center>Create a new player :</center>
            </h1>

						<v-form action="<%= Rails.application.routes.url_helpers.players_path %>" accept-charset="UTF-8" method="POST" ref="form" lazy-validation>
							<v-text-field name="player[pseudo]" label="Pseudo" v-model="pseudo" :rules="pseudoRules" required></v-text-field>
							<v-btn v-on:click="submit($event)" name="commit" data-disable-with="Save Player" color="primary">Save Player</v-btn>
						</v-form>
					</v-container>
				</v-content>
			</v-app>
		</div>

		<%= javascript_include_tag "vue.min" %>
    <%= javascript_include_tag "vuetify.min" %>

    <script type="text/javascript">
      var homepage = new Vue({
        el: "#suscribe",
        data: {
        	value: true,
        	pseudo: "",
        	pseudoRules: [
        		(v) => !!(v = v.trim()) || "Pseudo is required",
        		(v) => (v = v.trim()) && v.length > 2 || "Pseudo must be more than 2 characters"
        	]
        },
        methods: {
        	submit: function(e) {
        		if(this.$refs.form.validate()) {
        			e.target.closest("form").submit();
        		}
        	}
        }
      });
    </script>
	</body>
</html>

app/views/players/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    <title>Ruby Clicker</title>

    <%= stylesheet_link_tag "default.css" %>
    <%= stylesheet_link_tag "vuetify.min.css" %>

    <%= favicon_link_tag "/assets/ruby.png", rel: "icon", type: "image/png" %>

    <!-- <link rel="icon" type="image/png" href="/assets/ruby.png"> -->
    <link href="https://fonts.googleapis.com/css?family=Risque" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <div id="userpage">
      <v-app>
        <v-content>
          <v-container class="bloc">
            <v-layout>
							<v-flex xs12 sm6 offset-sm3>
								<v-card>
								  <v-card-media src="/assets/player.jpg" height="422px"></v-card-media>
								  <v-card-title primary-title>
								    <div>
								      <h3 class="headline mb-0"><%= @player.pseudo %></h3><br>
								      <v-chip label color="red" text-color="white">
								        <v-icon left>label</v-icon><%= "#{@player.ruby_count} rub" + (@player.ruby_count > 1 ? "ies" : "y") %>
								      </v-chip>
								    </div>
								  </v-card-title>
								  <v-card-actions>
								    <v-btn flat color="orange" @click="window.location = '<%= players_path %>'">Players list</v-btn>
								    <v-btn flat color="orange" @click="window.location = '<%= game_frame_url(@player) %>'">Play with this one!</v-btn>
								  </v-card-actions>
								</v-card>
							</v-flex>
		    		</v-layout>
          </v-container>
        </v-content>
      </v-app>
    </div>

    <%= javascript_include_tag "vue.min" %>
    <%= javascript_include_tag "vuetify.min" %>

    <script type="text/javascript">
      var userpage = new Vue({
        el: "#userpage"
      });
    </script>
  </body>
</html>